# Generated by Django 3.2.5 on 2021-08-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('longitude', models.IntegerField(default=0)),
                ('latitude', models.IntegerField(default=0)),
            ],
        ),
    ]
