# Generated by Django 3.2.5 on 2021-08-24 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_absen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='absen',
        ),
    ]
